config/routes.rb
Rails.application.routes.draw do
  root :to => 'games#home'
  resources :users, :only => [:new, :create, :index]

  resources :reviews, :only => [:new, :create, :index]

  resources :games

  # Not in the database!
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :reviews
    has_and_belongs_to_many :genres
end

# game is many to many with genre. but also has many reviews

app/models/genre.rb
class Genre < ApplicationRecord
    has_and_belongs_to_many :games
end

# many to many with games

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :game, :optional => true
end

# one to many with game.

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user 

    def check_for_admin 
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end

    def fetch_user
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present? # To logout non-existent users.
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

end


# 

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :check_for_login, :except => [:home]

  def home 
  end
  
  def index
    @games = Game.all
  end

  def new
    @games = Game.new
  end

  def create
    games = Game.create game_params
    redirect_to games_path 
  end

  def edit
    @games = Game.find params[:id]
  end

  def update
    games = Game.find params[:id] 
    games.update game_params
    redirect_to games 
  end

  def show
    @game = Game.find params[:id]
  end

  def destroy
    game = Game.find params[:id] 
    game.destroy 
    redirect_to games_path
  end

  private 

  def game_params 
    params.require(:game).permit(:title, :description, :image, :developer)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :check_for_login
    def index
        @reviews = Review.all 
    end

    def new 
        @review = Review.new
    end

    def create 
        review = Review.create review_params
        game = Game.find params[:review][:game_id]
        game.reviews << review
        redirect_to reviews_path
    end

    private 
    def review_params
        params.require(:review).permit(:title, :description)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Sorry, login failed"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index] # makes sure only admins can view all the users
  before_action :check_for_login, :only => [:index] # makes sure u have to have an account


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save 
      session[:user_id] = @user.id
    redirect_to root_path
    else
    render :new
  end
end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/games/_form.html.erb
<%= form_for @games do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :image %>
    <%= f.url_field :image, :required => true %>


    <%= f.submit %>

<% end %>

app/views/games/edit.html.erb
<h1>Edit Game</h1>

<%= render :partial => 'form', :class => "form-control", :class => "btn btn-secondary" %> 

<!-- same issue as new game page. didnt get bootstrap workin properly with these two -->

app/views/games/home.html.erb
<div class="home">
    <!-- home page. anyone can view -->
    <h1>Main Menu</h1>


    <p> <%= 'Welcome back ' + @current_user.email + '!' if @current_user.present? %> </p>
    <!-- only ppl that have made an acc see this msg pop up -->
    <p>

    Delve into this site and view our collection of games! If a game you love isn't here, simply add it to our vast library of games! You can also add reviews to any game you'd like.

    </p>

</div>

<div class="img1">

    <%= image_tag("https://i.imgur.com/e5KWytf.png") %>

</div>

app/views/games/index.html.erb
<div class="row"> <!-- bootstrap for all games page. want to add an image too, the two empty classes are just to keep free space on either side of the middle one** -->
    <div class="col-md-3">


    </div>

    <div class="col-md-3">

        <h1>All games</h1>
<br>
        <h2>Total games: <%= @games.count %></h2>
<br>
        <ul>
            <% @games.each do |game| %>
                <li class="link">
                    <%= link_to game.title, game %>
                </li >
            <% end%>
        </ul>
    </div>

    <div class="col-md-3">


    </div>

</div>

app/views/games/new.html.erb
<div class="newgame">

    <h1>Add a new game to the collection!</h1>

    <%= render :partial => 'form', :class => 'form-control', :class => "btn btn-secondary" %> <!-- not sure how to use bootstrap with render :/ -->

</div>

app/views/games/show.html.erb
<!-- more bootstrap for the invidual games page.-->

<div class="container">

  <div class="row">

    <div class="col">
      <h3>Release date: <%= @game.release %></h3>
    </div>
    
    <div class="col-5">
        <h1><%= @game.title %></h1>
        <%= link_to 'Edit game', edit_game_path if @current_user.admin? %>
        <%= link_to "Delete Game", @game, :method => 'delete', :data => { :confirm => 'Please confirm.' } if @current_user.admin? %>
    </div>

    <div class="col">
        <h3>
            Developer: <%= @game.developer %>
        </h3>
    </div>
</div>

<div class="row">

    <div class="col">
        <h3>
            Description:
        </h3>
        <p>
            <%= @game.description %>
        </p>
    </div>
    
    <div class="col-5">
        <p>
            <%= image_tag (@game.image), :class => "img-fluid" if @game.image.present?%>
        </p>
    </div>

    <div class="col">
        <h3>
            Genre: <%= @game.genres.pluck(:name).join ', ' %>
        </h3>
    </div>
</div>

<div class="row">

    <div class="col">
    
    </div>

    <div class="col-5">
        <h2>Reviews</h2>
        <% @game.reviews.each do |review| %>
            <h3> <%= review.title %> </h3>
            <p> <%= review.description %> </p>
        <% end %>
    </div>  <!-- shows the games reviews,descrp, title, image and dev on one page-->

    <div class="col">
    
    </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark" id="navigation">

        <%= link_to 'Home', root_path %>
        <% if @current_user.present?%>
        <%= link_to "All users", users_path if @current_user.admin?%> <!-- makes sure only admins can see all users page-->
        <%= link_to 'All Games', games_path  %>
        <%= link_to 'Add Game', new_game_path %>
        <%= link_to "Create review", new_review_path %>
        <%= link_to "Logout #{ @current_user.email }", login_path, :method => 'delete' %>
      <% else %>
  
        <%= link_to 'Login', login_path %>

      <% end %>
    </nav>
    
    <%= yield %>
    
  </body>
</html>

app/views/reviews/index.html.erb
<h1>All reviews</h1>

<% @reviews.each do |review| %>

    <ul><strong><%= review.title %></strong></ul> <!-- have not properly connected users to reviews so this page can't be accessed unless u type 'reviews' in the search bar. -->
    <ul><%= review.description %></ul>

<% end %>

app/views/reviews/new.html.erb
<div class="newreview">

<!-- another page. lets u create a new review. has bootstrap to make it look pretty -->

<h1>Write a new review</h1>

<% if @review.errors.any? %>
    <ol>
        <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ol>
<% end %>

<%= form_for @review do |f| %>

    <div class="form-group">

        <%= f.label :title %>
        
        <%= f.text_field :title, :class => "form-control" %>

    </div>

    <div class="form-group">

        <%= f.label :description %>

        <%= f.text_field :description, :class => "form-control" %>

    </div>

    <div class="form-group">

        <%= f.label :games_id %>

        <%= f.select :game_id, Game.pluck(:title, :id), :include_blank => true, :class => "form-control" %>

    </div>

        <%= f.submit "Create a new review!", :class => "btn btn-secondary" %>
    <% end %>

</div>

app/views/session/new.html.erb
<div class="signin">

<h1>Log In</h1>

<%= form_tag login_path do %>

    <div class="form-group">

        <%= label_tag :email %>

        <%= email_field_tag :email, nil, :class => "form-control" %>

    </div>

    <div class="form-group">

        <%= label_tag :password %>

        <%= password_field_tag :password, nil, :class => "form-control" %>

    </div>

    <%= submit_tag "Login!", :class => "btn btn-secondary" %>

<% end %>

<p>If you don't yet have an account, please sign up here. <%= link_to "here", new_user_path %>.</p>

</div>

app/views/users/index.html.erb
<h1>All users</h1>

<h2><%= @users.count %> registered users</h2> <!-- the page of users. only admins can view this cos of the code in app html-->

<ul>
    <% @users.each do |user| %>
        <p> <%= user.email %> </p>
    <% end %>
</ul>

app/views/users/new.html.erb
<div class="signup"> <!-- simple bootstrap for the new user page -->

<h1>Sign up</h1>

<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ol>
<% end %>

<%= form_for @user do |f| %>

    <div class="form-group">

        <%= f.label :email %>
        <%= f.email_field :email, :class => "form-control" %>

    </div>

    <div class="form-group">

        <%= f.label :password %>

        <%= f.password_field :password, :class => "form-control" %>

    </div>


    <div class="form-group">

        <%= f.label :password_confirmation %>

        <%= f.password_field :password_confirmation, :class => "form-control" %>

    </div>
    
    <%= f.submit "Sign up!", :class => "btn btn-secondary" %>
    
<% end %>

</div>